# Generated by Django 5.1.3 on 2024-11-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="your_comment",
            field=models.TextField(max_length=300),
        ),
    ]
